### PR TITLE
Dev cuda11

### PR DESCRIPTION
**Pull request by wztzjhn**
CUDA has evolved for a while since the last commit. With the default CUDA-11 on Ubuntu 22.04, FastKPM no longer compiles. This pull request contains mainly:
1. BlockDim==1 sparseBSR matrix is no longer allowed by CUDA to operate on matrix-vector and matrix-matrix products. In this case, I try to fall back to CSR routines. However, CSR routines are also completely deprecated in CUDA. So more dramatic changes are made (see details).
2. A minor change on the FindArmadillo.cmake: now it is an independent file under cmake_modules, making it easier to find Armadillo in case some systems does not recognize it easily.
3. I converted deallocate() to a destructor for CuVec class, so memory should be automatically released (many lines of the code doing deallocation are removed now).
4. I added a class CuSpMat, to make the newly added CSR * vector and CSR * matrix operation more compact.
5. moments2_v1 was not on engine_MPI, now fixed.

Note: in the Kondo repo, it seems now I have to link to CUDA explicitly (previously omitted), otherwise it is giving an error message about missing THREADS::THREADS. I have also changed several places under Kondo, but will need some time to cherry-pick only the essential ones to make a separate pull-request there.

### CODE REVIEW

**Comment by wztzjhn** [comment]
Actually, I found the updated code requires CUDA >= 11.3 (my Ubuntu 22.04 is using CUDA 11.5; the newest CUDA is 11.7). For slightly older versions (>=11.0), the CSR matrix-vector routine has to be slightly changed (basically the name of the algorithm used in CSR matrix-vector product). For even older versions (<11.0), the new CUDA grammar is completely incompatible. 

We should either simply require CUDA-11.3 in cmake, or add macros to compile the code differently for different minor.patch versions (a bit ugly...)

The problem seems simply that CUDA-11 changed too many places. For a discussion, see:
https://github.com/mfem/mfem/issues/2336

**Comment by kbarros** [comment]
Hi Zhentao, thanks for updating this. It seems like you have put a lot of thought into it, and I don't have time to catch up on these CUDA details. I'm willing to go ahead and merge whenever you think it's ready. We could also nominate your repo to be the "main" one for this project? (Let me know how best to do that.)

**Comment by wztzjhn** [comment]
Hi Kip, it seems to me the the current pull request is almost ready. If you agree, the only change before merging is to require CUDA>=11.3 in the cmake file. To allow users to run with older versions of CUDA, we can probably tag the commit before merging as an old release?

**Comment by wztzjhn** [comment]
And thanks for offering this, It sounds great if you make my fork as the "main". The only concern for you is then I tend do slightly more aggressive changes under my fork...

**Comment by kbarros** [comment]
Awesome work!

**Pull request merged**
